Makefile, README.md, docker-compose.yml
- Make it possible to check out assets (for now, just the
wp-gutenberg-epfl plugin) under /wp/5 (from the perspective of code
inside the containers)
- `make wp5` action with rudimentary documentation
=> An embryo of WordPress 5 support

Makefile
Said plugin was extracted out of jahia2wp using the following script:
```
git clone ~/Dev/WordPress/volumes/wp/jahia2wp epfl-menus
cd epfl-menus
git checkout origin/release2018
git checkout -b release2018
git filter-repo --path data/wp/wp-content/plugins/epfl-menus \
--path-rename 'data/wp/wp-content/plugins/epfl-menus/epfl-menus-admin.css:epfl-menus-admin.css' \
--path-rename 'data/wp/wp-content/plugins/epfl-menus/epfl-menus-admin.js:epfl-menus-admin.js' \
--path-rename 'data/wp/wp-content/plugins/epfl-menus/epfl-menus.php:epfl-menus.php' \
--path-rename 'data/wp/wp-content/plugins/epfl-menus/wpcli.php:wpcli.php' \
--path-rename 'data/wp/wp-content/plugins/epfl-menus/lib:lib' \
--force
git checkout -B master
git remote add origin git@github.com:epfl-idevelop/wp-plugin-epfl-menus.git
git …
```
=> Check out the epfl-menus plugin from its new home

Makefile, docker-compose.yml
- Need two new volumes: /wp-ops contains the wp-ops checked out tree;
/usr/local/bin is doctored the same way /wp is (using a mix of
symlinks and binaries extracted from the mgmt image)
- Add appropriate Makefile pipework
=> [feature] Run new-site.sh from its checked out copy

README.md, devscripts/copy-enac-from-prod.sh
- Uses `wp db dump` / `wp db restore` + `wp search-replace`, as per  https://confluence.epfl.ch:8443/pages/viewpage.action?pageId=75662209
- Symlinks sites in a crude fashion (enough for EPFL plug-ins and themes to load)
- Images are *not* synced (5Gb+ to copy? No thanks) — I suppose we could be smarter in the `wp search-replace` to hotlink them out of the production sites
=> [feature] Script to copy a hierarchy of WordPress sites from production

Makefile
After [wp-ops' #157](https://github.com/epfl-idevelop/wp-ops/pull/157), wp-ops has
sub-gits and needs `make checkout` to become fully operational.
Arrange for wp-dev to pass on the `make checkout` goodness.
=> [feature] `make checkout` now daisy-chains into wp-ops

Makefile, devscripts/ensure-git-clone.sh
Pour que le `make`  utilise le nouveau repo du plugin wp-plugin-epfl-404 , il faut faire un 
`touch volumes/wp/5/wp-content`
Cette comande va changer le timestamp et aura pour conséquence la mise à jour et donc l'utilisation du nouveau repo pour le plugin epfl-404
```
git filter-repo --path data/wp/wp-content/plugins/epfl-404 \
--path-rename 'data/wp/wp-content/plugins/epfl-404/epfl-404.php:epfl-404.php' \
--path-rename 'data/wp/wp-content/plugins/epfl-404/inc:inc' \
--force
```
=> Use new repo of epfl-404 plugin

devscripts/myip, devscripts/php-xdebug
Darwin systems do not like the xdebug.remote_connect_back strategy, so a check is made and we use it only for Linux systems
=> Readd the ip declaration on Darwin systems when using xdebug

Makefile, README.md, docker-compose.yml
Following the rename of the epfl-idevelop GitHub organization to epfl-si today, we want to update all pointers (despite the old addresses still working for now).
=> [janitor] github.com/epfl-idevelop → github.com/epfl-si

Makefile, docker-compose.yml
The tags are phony, but they need to be kept in sync between wp-dev (for dev builds) and wp-ops (for production builds)
=> [fix] Standardize on "epflsi" for Docker tags

Makefile
- Overwrite files chmod'd read-only (e.g. git packs and objects)
- Don't attempt to restore file modification times
- Exclude EPFL* plugins like we did on epfl* plugins (the latter being
good enough on Mac OS X's case-insensitive file system)
=> [fix] Work around various `tar` failure modes on Linux

Makefile
Test like this:
```
rm .make.vars
touch .docker-all-images-built.stamp
make up
```
=> [fix] Put _HOST_TAR_X into .make.vars like the other platform variables

Makefile, docker-compose.yml
https://github.com/epfl-si/wp-ops/commit/f2091c2d49ddde025e10c5e8f2852f4551b44024 retires the local copy of the `cortneyray/wp-cli-polylang` patched wp-cli plug-in, which was turned into a [proper GitHub fork](https://github.com/epfl-si/wp-cli-polylang) instead. Check out and use the latter as part of the wp-dev workspace.
=> [feature] Check out newly created github.com/epfl-si/wp-cli-polylang

Makefile
This parallels https://github.com/epfl-si/wp-ops/pull/315
- Remove all WP4-specific code, special cases for plugin activations etc.
Also while we are at it :
- Fix `make OUTSIDE_EPFL=1`
- Do call `new-wp-site` as part of `make up`, resolving a long-standing TODO item
=> [feature] Off with wordpress 4

Makefile
Les derniers plugins ont été déplacés dans leur repo respectif.
Cette PR utilise ces nouveaux dans wp-dev
https://github.com/epfl-si/wp-ops/pull/327
=> [fix] Use new GIT repo of plugins

Makefile
This pull request goes with https://github.com/epfl-si/wp-ops/pull/430.
We suffer from occasional build failures because of a BadZipFile error caused by wp-manager.epfl.ch truncating the downloads (for reasons yet unknown). To remediate this, we set up a new bucket on s3.epfl.ch and put our purchased software assets there (for the time being, the list consists of the wp-media-folder and wpforms plugins).
- Pass required --s3-* flags to `install-plugins-and-themes.py` via `--build-arg INSTALL_AUTO_FLAGS`
- Decrypt secrets from Keybase and EYAML (w/ poor man's Jinja parser in Perl)
- Give the operator a clue if no eyaml binary can be found
=> [feature] Install purchased assets from S3

Makefile
This is required for Linux, which (unlike MacOS) won't map permissions
back to the user running Docker.
=> [fix] `make up`: ensure correct permissions on volumes/srv

Makefile, docker-compose.yml
This fix allows to test 2867cfc9a27c85abab005051f2cf2fa09a41a98e locally 
(with wp-dev) and be able to send mail.
=> [fix] source SMTP secret

Makefile, devscripts/functions.sh, docker-compose.yml
As stated in the compose documentation
(https://docs.docker.com/compose/reference/), from the end of June 2023 Compose V1 won’t be supported anymore and will be removed from all Docker Desktop versions. You can run Compose V2 by replacing the hyphen (-) with a space, using `docker compose`, instead of `docker-compose` and this is exactly what's it's intended in this commit.
=> [fix] use of the Docker CLI (Compose V2)

README.md, devscripts/local-restore-from-restic.sh
Restore from within the mgmt container using a `restic dump | docker exec tar` pipeline, so that we don't have to deal with permissions as seen from outside the container.
Pair-programmed with @rosamaggi
=> [fix] Bypass permissions problems with `restic restore`

devscripts/local-restore-from-restic.sh
As the S3 bucket were changed last year, the default bucket needed an update. The grepping of the secret in Keybase needed more line to find them.
=> [fix] local-restore-from-restic.sh

Makefile
Now it's always `src` — The `docker-compose.yml` already assumes as much anyway.
=> [unfeature] Eliminate `$(WP_SRC_DIR)` variable

Makefile, devscripts/ensure-git-ssh-url
This will change all remotes URL of "epfl-si" repositories to git@github.com: instead of https://github.com/
=> [feature] Make all git repositories “pushable”

devscripts/curl-authenticated-quay
This is Docker's own internal credential score (in use on Linux)
=> [feature] Add `secretservice` credStore

Makefile, devscripts/mariadb-general-log
Put it back in working order (mostly by `s/mysql/mariadb/`).
=> [fix] Observing MariaDB query log

Makefile
Build the wp-cron image and push it from one's workstation.
=> [feature] Support `wp-cron` in the development environment
